# Generated by Django 5.0 on 2025-11-06 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CS 2340', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('domain', models.CharField(blank=True, help_text='e.g., gatech.edu', max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('grade_level', models.CharField(choices=[('frosh', 'First-year'), ('soph', 'Sophomore'), ('jun', 'Junior'), ('sen', 'Senior'), ('grad', 'Graduate'), ('other', 'Other')], max_length=10)),
                ('major', models.CharField(blank=True, max_length=120)),
                ('availability_json', models.JSONField(blank=True, default=dict, help_text="e.g., {'mon':[['18:00','20:00']], 'wed':[['19:00','21:00']]}")),
                ('modality_pref', models.CharField(choices=[('in_person', 'In-person'), ('online', 'Online'), ('either', 'Either')], default='either', max_length=10)),
                ('campus_name', models.CharField(blank=True, help_text='e.g., Clough Commons', max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('commute_radius_miles', models.DecimalField(decimal_places=1, default=5.0, help_text='0.0-99.9', max_digits=4)),
                ('study_prefs', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('visibility', models.CharField(choices=[('same_school', 'Same-school only'), ('public', 'Platform-wide')], default='same_school', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_courses', models.ManyToManyField(blank=True, related_name='enrolled_profiles', to='profiles.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profiles.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='profiles.university'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['university', 'code'], name='profiles_co_univers_c66b26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('university', 'code')},
        ),
    ]
