# Generated by Django 5.0 on 2025-11-06 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code_text', models.CharField(blank=True, help_text='Fallback if course missing', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('modality', models.CharField(choices=[('in_person', 'In-person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='in_person', max_length=10)),
                ('meeting_link', models.URLField(blank=True, help_text='For online/hybrid; members only')),
                ('capacity', models.PositiveSmallIntegerField(default=5)),
                ('current_size', models.PositiveSmallIntegerField(default=1, help_text='Owner included; keep in sync')),
                ('cadence', models.CharField(choices=[('one_off', 'One-off'), ('weekly', 'Weekly')], default='weekly', max_length=10)),
                ('weekday', models.CharField(blank=True, choices=[('mon', 'Mon'), ('tue', 'Tue'), ('wed', 'Wed'), ('thu', 'Thu'), ('fri', 'Fri'), ('sat', 'Sat'), ('sun', 'Sun')], help_text='Weekly only', max_length=3)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags: midterm 1, op-amps', max_length=200)),
                ('join_policy', models.CharField(choices=[('owner_approve', 'Owner approves'), ('auto_accept', 'Auto-accept')], default='owner_approve', max_length=15)),
                ('visibility', models.CharField(choices=[('same_school', 'Same-school'), ('public', 'Public')], default='same_school', max_length=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='profiles.course')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='locations.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='profiles.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='buddies.buddylisting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('waitlisted', 'Waitlisted')], db_index=True, default='requested', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='buddies.buddylisting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=10)),
                ('new_status', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='buddies.buddylisting')),
            ],
            options={
                'verbose_name_plural': 'Listing Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('join_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='buddies.joinrequest')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='buddies.buddylisting')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='buddylisting',
            index=models.Index(fields=['university', 'status', 'created_at'], name='buddies_bud_univers_73ddc6_idx'),
        ),
        migrations.AddIndex(
            model_name='buddylisting',
            index=models.Index(fields=['course', 'status'], name='buddies_bud_course__b2d4c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('listing', 'student')},
        ),
        migrations.AddIndex(
            model_name='joinrequest',
            index=models.Index(fields=['student', 'status'], name='buddies_joi_student_fb38b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('listing', 'student')},
        ),
    ]
